name       : mit-scheme
version    : 10.1.4
release    : 2
source     :
    - https://ftp.gnu.org/gnu/mit-scheme/stable.pkg/10.1.4/mit-scheme-10.1.4-x86-64.tar.gz : 58632c6950e87e77f25c7d6c32604dcdffd91fa327545414ac6907d154d87585
license    : GPL-2.0-or-later
component  : programming
summary    : MIT/GNU Scheme is an implementation of the Scheme programming language.
description: |
    MIT/GNU Scheme is an implementation of the Scheme programming language, providing an interpreter, compiler, source-code debugger, integrated Emacs-like editor, and a large runtime library.
setup      : |
    cd src
    %configure
build      : |
    %make -C src
install    : |
    %make_install -C src
