name       : mit-scheme
version    : 10.1.5
release    : 3
source     :
    - https://ftp.gnu.org/gnu/mit-scheme/stable.pkg/10.1.5/mit-scheme-10.1.5-x86-64.tar.gz : 470a41117add68534980f32543952a3f763b45b55d8d70fd3910a535aed358e5
license    : GPL-2.0-or-later
component  : programming
summary    : MIT/GNU Scheme is an implementation of the Scheme programming language.
description: |
    MIT/GNU Scheme is an implementation of the Scheme programming language, providing an interpreter, compiler, source-code debugger, integrated Emacs-like editor, and a large runtime library.
setup      : |
    cd src
    %configure
build      : |
    %make -C src
install    : |
    %make_install -C src
