name       : mit-scheme
version    : 10.1.9
release    : 5
source     :
    - https://ftp.gnu.org/gnu/mit-scheme/stable.pkg/10.1.9/mit-scheme-10.1.9-x86-64.tar.gz : ac67b7a357b06239b61d3707924bfc43f941c5b4f15491956f6b020923d5ebe8
license    : GPL-2.0-or-later
component  : programming
summary    : MIT/GNU Scheme is an implementation of the Scheme programming language.
description: |
    MIT/GNU Scheme is an implementation of the Scheme programming language, providing an interpreter, compiler, source-code debugger, integrated Emacs-like editor, and a large runtime library.
setup      : |
    cd src
    %configure
build      : |
    %make -C src
install    : |
    %make_install -C src
