name       : mit-scheme
version    : 10.1.3
release    : 1
source     :
    - http://ftp.gnu.org/gnu/mit-scheme/stable.pkg/10.1.3/mit-scheme-10.1.3-x86-64.tar.gz : 1371effeccb8f9b5432b04d43ceedb4feb125cfaec0a1992de6af0320063a70e
license    : GPL-2.0-or-later
component  : programming
summary    : MIT/GNU Scheme is an implementation of the Scheme programming language.
description: |
    MIT/GNU Scheme is an implementation of the Scheme programming language, providing an interpreter, compiler, source-code debugger, integrated Emacs-like editor, and a large runtime library.
builddeps  :
    - pkgconfig(ncursesw)
setup      : |
    cd src
    %configure
build      : |
    %make -C src
install    : |
    %make_install -C src
