name       : mit-scheme
version    : 10.1.11
release    : 7
source     :
    - https://ftp.gnu.org/gnu/mit-scheme/stable.pkg/10.1.11/mit-scheme-10.1.11-x86-64.tar.gz : 32c29fe08588ed325774113bac00dce72c2454955c64ba32fc40f30db011c21c
license    : GPL-2.0-or-later
component  : programming
summary    : MIT/GNU Scheme is an implementation of the Scheme programming language.
description: |
    MIT/GNU Scheme is an implementation of the Scheme programming language, providing an interpreter, compiler, source-code debugger, integrated Emacs-like editor, and a large runtime library.
setup      : |
    cd src
    %configure
build      : |
    %make -C src
install    : |
    %make_install -C src
