name       : mit-scheme
version    : 10.1.6
release    : 4
source     :
    - https://ftp.gnu.org/gnu/mit-scheme/stable.pkg/10.1.6/mit-scheme-10.1.6-x86-64.tar.gz : 9b024bf3085b440ea2293f554fba4a792504a5af6a3741811902aa18d622dfa4
license    : GPL-2.0-or-later
component  : programming
summary    : MIT/GNU Scheme is an implementation of the Scheme programming language.
description: |
    MIT/GNU Scheme is an implementation of the Scheme programming language, providing an interpreter, compiler, source-code debugger, integrated Emacs-like editor, and a large runtime library.
setup      : |
    cd src
    %configure
build      : |
    %make -C src
install    : |
    %make_install -C src
