name       : mit-scheme
version    : '12.1'
release    : 10
source     :
    - https://ftp.gnu.org/gnu/mit-scheme/stable.pkg/12.1/mit-scheme-12.1-x86-64.tar.gz : 8cfbb21b0e753ab8874084522e4acfec7cadf83e516098e4ab788368b748ae0c
license    : GPL-2.0-or-later
component  : programming
summary    : MIT/GNU Scheme is an implementation of the Scheme programming language.
description: |
    MIT/GNU Scheme is an implementation of the Scheme programming language, providing an interpreter, compiler, source-code debugger, integrated Emacs-like editor, and a large runtime library.
setup      : |
    cd src
    %configure
build      : |
    %make -C src
install    : |
    %make_install -C src
